# Generated by Django 2.0.1 on 2018-04-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('score', models.IntegerField(serialize=False)),
                ('id', models.IntegerField(primary_key=True)),
            ],
        ),
    ]
